//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAMVC.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TAC_User
    {
        public TAC_User()
        {
            this.TAC_Classified = new HashSet<TAC_Classified>();
        }
    
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        [Display(Name = "Password")]
        public string UPassword { get; set; }
        [Display(Name = "First Name")]
        public string First_Name { get; set; }
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Country { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<TAC_Classified> TAC_Classified { get; set; }
        public virtual TAC_Country TAC_Country { get; set; }
    }
}
