//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAMVC.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAC_Category
    {
        public TAC_Category()
        {
            this.TAC_Classified = new HashSet<TAC_Classified>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryImage { get; set; }
    
        public virtual ICollection<TAC_Classified> TAC_Classified { get; set; }
    }
}
